// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRGZcCqwBPoc2jJiqKsRzY5BIuf5W-F4',
    appId: '1:6689500504:android:f3e73aa07ff1977b6d092d',
    messagingSenderId: '6689500504',
    projectId: 'chairy-e-commerce-app',
    storageBucket: 'chairy-e-commerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDELi5vmo7VYZPRmeFYx5cJFik5981lPR4',
    appId: '1:6689500504:ios:46a45ee197e0fdde6d092d',
    messagingSenderId: '6689500504',
    projectId: 'chairy-e-commerce-app',
    storageBucket: 'chairy-e-commerce-app.firebasestorage.app',
    androidClientId: '6689500504-ql966rus863872isre5gbra1hph608fp.apps.googleusercontent.com',
    iosClientId: '6689500504-nethqfd06qpqs42lus1jao29aolvdeps.apps.googleusercontent.com',
    iosBundleId: 'com.example.chairyECommerceApp',
  );
}
