// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_3DoTRDkzvStHpb4SXKsWs5-eb_xXeZ0',
    appId: '1:6689500504:web:980c2646580308736d092d',
    messagingSenderId: '6689500504',
    projectId: 'chairy-e-commerce-app',
    authDomain: 'chairy-e-commerce-app.firebaseapp.com',
    storageBucket: 'chairy-e-commerce-app.firebasestorage.app',
    measurementId: 'G-0GRBB1YR5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRGZcCqwBPoc2jJiqKsRzY5BIuf5W-F4',
    appId: '1:6689500504:android:f3e73aa07ff1977b6d092d',
    messagingSenderId: '6689500504',
    projectId: 'chairy-e-commerce-app',
    storageBucket: 'chairy-e-commerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDELi5vmo7VYZPRmeFYx5cJFik5981lPR4',
    appId: '1:6689500504:ios:46a45ee197e0fdde6d092d',
    messagingSenderId: '6689500504',
    projectId: 'chairy-e-commerce-app',
    storageBucket: 'chairy-e-commerce-app.firebasestorage.app',
    iosBundleId: 'com.example.chairyECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDELi5vmo7VYZPRmeFYx5cJFik5981lPR4',
    appId: '1:6689500504:ios:46a45ee197e0fdde6d092d',
    messagingSenderId: '6689500504',
    projectId: 'chairy-e-commerce-app',
    storageBucket: 'chairy-e-commerce-app.firebasestorage.app',
    iosBundleId: 'com.example.chairyECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_3DoTRDkzvStHpb4SXKsWs5-eb_xXeZ0',
    appId: '1:6689500504:web:8684915e9406e1726d092d',
    messagingSenderId: '6689500504',
    projectId: 'chairy-e-commerce-app',
    authDomain: 'chairy-e-commerce-app.firebaseapp.com',
    storageBucket: 'chairy-e-commerce-app.firebasestorage.app',
    measurementId: 'G-MJZJHS0W7N',
  );
}
